name: Windows build
on: [push]

jobs:
  run_tests:
    runs-on: windows-latest
    steps:

    - run: git config --global core.autocrlf input

    - uses: actions/checkout@v3

    - uses: cygwin/cygwin-install-action@master
      with:
        platform: 'amd64'
        packages: |
          cygwin-devel,
          gcc-core,
          libusb1.0,
          libusb1.0-devel

    # - run: cygcheck -c cygwin; cygcheck -l cygwin | wc -l
    # - run: pwd.exe; find /usr/include

    - run: bash build_for_windows.sh

    - run: find .

    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: xvcd-pico
        path: |
          xvcd-pico.exe
          cygusb-1.0.dll
          cygwin1.dll
